INSERT INTO userA (username, name, password, region, age, language, platform) VALUES
('frankharrison', 'Rebecca Elliott', 'iZP9FsNSfb', 'Guinea-Bissau', 57, 'Aragonese', 'WIN'),
('jennifermiller', 'Zachary Norman', '3S4Zsl8yX9Q', 'Seychelles', 55, 'Tsonga', 'WIN'),
('emartinez', 'Sean Edwards', 'zqhSM4QQu3Cy', 'Korea', 21, 'Samoan', 'MAC'),
('michael20', 'Howard Sparks', 'mzPVgGNB9RyVk3MbJ', 'Holy See (Vatican City State)', 39, 'Somali', 'LNX'),
('carrillokristine', 'Jennifer Thompson', 'TuWbMvtIYnQE2Sc', 'Guam', 47, 'Urdu', 'WIN'),
('christine15', 'Nathaniel Pineda', '9RChJo8uNYDnNU1uB', 'Slovenia', 20, 'Urdu', 'WIN'),
('crawfordchristopher', 'Nicolas Flores', 'zi51pwuHPQlAzIw4jW', 'Guatemala', 18, 'Cree', 'WIN'),
('christopherboyd', 'Joanne Heath', 'Ab8RjcNXSg', 'Saint Kitts and Nevis', 55, 'Swahili', 'LNX'),
('lperez', 'Lawrence Mitchell', 'wScyxTsS8OOZtQwg0HYl', 'South Africa', 53, 'Sichuan Yi', 'WIN'),
('caitlyn97', 'Andrew Long', '0dnCRDNhu9iUiJp', 'Grenada', 35, 'Catalan', 'MAC'),
('flewis', 'Susan Bennett', 'NlKAurnpa', 'Libyan Arab Jamahiriya', 23, 'Turkish', 'LNX'),
('murraybrandon', 'Maria Wilson', 'QlY9RFZMsJQoT', 'Christmas Island', 63, 'Somali', 'MAC'),
('hernandezjessica', 'Marcus Martin', '4wl9pAowX30mRPB4aqA8', 'Lesotho', 42, 'Latvian', 'MAC'),
('lgarcia', 'Joseph Robbins', 'Pavm9mnu5JZJZCJjxF', 'Sierra Leone', 61, 'Luxembourgish', 'LNX'),
('meagan59', 'Susan Armstrong', 'A9VcgRmiqdwCIR4BxLdj', 'Chile', 41, 'Kazakh', 'LNX'),
('beth76', 'Christopher Allen MD', '6OVbDlq9FV9x2bZyE', 'Thailand', 50, 'Turkish', 'WIN'),
('kristy67', 'Carmen Liu', 'F7XoP929eV9rwR', 'Togo', 55, 'Danish', 'WIN'),
('rogersamy', 'Samantha Dominguez', 'kxafmyvq7C2THAmZQpC', 'Afghanistan', 38, 'Inupiaq', 'WIN'),
('ibarrachristopher', 'Jason Campbell', '1g0FTKbReWMINfJL2', 'New Zealand', 41, 'Hindi', 'WIN'),
('walterstevens', 'John Garcia', 'qEyy4zBwJS1ycbscF2', 'Lithuania', 35, 'Finnish', 'MAC'),
('erinhardin', 'Cody Phillips', 'p8q7wVVh7zKzSx695Y8', 'Saint Helena', 47, 'Kalaallisut', 'MAC'),
('ycuevas', 'Jessica Smith', 'qWQAwKNiM', 'Ghana', 64, 'Lao', 'MAC'),
('courtney23', 'Tricia Tran', 'WYskwuWTrFH', 'India', 49, 'Malagasy', 'MAC'),
('lori75', 'Tina Soto', 'R5PRSznV2H', 'Guam', 21, 'Hungarian', 'LNX'),
('shellylawson', 'James Douglas', 'YCtguSFiWeLpxw6A', 'Cape Verde', 18, 'Thai', 'WIN'),
('harrymiller', 'Janet Johnson', 'rWozvRVI64O', 'Venezuela', 43, 'Somali', 'MAC'),
('davidcharles', 'Cassidy Lewis', 'u6wV3yEp5Vp', 'Cook Islands', 54, 'Komi', 'MAC'),
('jsmith', 'Dustin Newton', 'QvTWRQaIvp9', 'Holy See (Vatican City State)', 38, 'Herero', 'WIN'),
('johnsonelizabeth', 'Cameron Meza', 'mJsPmAxLbqOHhz7T', 'Kenya', 35, 'Sango', 'LNX'),
('butlerjeremy', 'Jeanne Paul', 'PqtvqN0R9k04RQB', 'Albania', 25, 'Kongo', 'LNX'),
('alexisgarcia', 'Denise Short', 'KW2fm7bk', 'Swaziland', 64, 'Tagalog', 'WIN'),
('egibbs', 'Andrew Potter', 'ruz7tF2hWC556K', 'Canada', 36, 'Luba-Katanga', 'LNX'),
('qhendricks', 'Kathleen Palmer', 'zpYTd7Zrv54G', 'India', 50, 'Javanese', 'WIN'),
('angela57', 'Christopher Sanchez', 'YiQ2UmGur4uiUpQ8knZE', 'Bouvet Island (Bouvetoya)', 21, 'Bihari languages', 'WIN'),
('contrerasaaron', 'James Howell', 'F3FrOsMqnH', 'Ghana', 25, 'Kinyarwanda', 'LNX'),
('paul82', 'Claire Johnson MD', 'tR3ewe3qh7', 'Yemen', 49, 'Fijian', 'LNX'),
('alexismann', 'William Mason', 'DJQJ7dlvjI0igUU', 'Christmas Island', 27, 'Korean', 'LNX'),
('gatesbrandi', 'Angela Glover', 'AWYQQfDPAaewgP', 'Portugal', 55, 'Ido', 'LNX'),
('gregory66', 'Matthew Flores', 'MZmlTrH4SVp2y', 'Hungary', 25, 'Korean', 'LNX'),
('spencer35', 'William Short', 'NXVa9w8k3RD0A2jpaIe', 'Dominica', 27, 'Greek', 'LNX'),
('stephanie50', 'Eric Hernandez', 'vbjCH4IolHqQopRQ', 'Qatar', 61, 'Estonian', 'MAC'),
('frostanthony', 'Joseph Reyes', 'ULmPpFFWpRQGHsD', 'Rwanda', 61, 'Telugu', 'WIN'),
('john46', 'Dr. Juan Lopez', '5soITfKMdQkM', 'French Southern Territories', 47, 'Herero', 'MAC'),
('john50', 'Charlotte Ewing MD', '9d5YYjs8Rxtcl1qIiq1', 'Guam', 43, 'Kurdish', 'LNX'),
('elizabethmontgomery', 'Leslie Brooks', '3kAb614OzVzo', 'India', 54, 'Sundanese', 'LNX'),
('kimberly05', 'Bryan Jackson', 'OliKlcNZQdqRyWo', 'Angola', 32, 'Chichewa', 'LNX'),
('amanda86', 'Brittany Crosby', 'VWlpMnvwjvxxo01HxI', 'Svalbard & Jan Mayen Islands', 19, 'Sichuan Yi', 'LNX'),
('mariah44', 'Matthew Lewis', 'LaSYWnKAoScRWxu', 'Nepal', 45, 'Oriya', 'WIN'),
('wattscameron', 'Jonathan Morgan', '4vLDNTVoq', 'Oman', 59, 'Kinyarwanda', 'LNX'),
('nbarton', 'Renee Robinson', 'Ddu74H74qDHFt3N', 'Cape Verde', 46, 'Xhosa', 'MAC'),
('nathanjackson', 'Patrick Brown', 'z8efPMLyTvZfqqV', 'Bosnia and Herzegovina', 23, 'Sotho, Southern', 'LNX'),
('fbell', 'Susan Matthews', '30zeZkzC6IpdM90', 'Finland', 65, 'Malagasy', 'WIN'),
('kylelara', 'Kristopher Ramirez', 'Y1wpIvX0GaHAvlVO', 'Sweden', 57, 'Pushto', 'LNX'),
('obecker', 'Jennifer Scott', 'ZiVi5wC8khb4f6AT', 'Liberia', 28, 'Tahitian', 'MAC'),
('fbrown', 'Natalie Simmons', 'fdiEIEejaQIc', 'Zimbabwe', 43, 'Interlingue', 'LNX'),
('arnoldemily', 'Kimberly Odom', 'NTgWw3v8haYI', 'Monaco', 44, 'Fulah', 'MAC'),
('upowers', 'Anthony Adkins', 'ctZLPWdkCXzyBxo0', 'Turkey', 21, 'Avestan', 'WIN'),
('thomasewing', 'Lisa Hall', 'DBQ7mhT6N92hZ7gK1S4', 'Malta', 62, 'Rundi', 'WIN'),
('ikennedy', 'David Larson', 'wHr6zp4e', 'Sudan', 56, 'Azerbaijani', 'MAC'),
('mikaylabradshaw', 'Tyler Russell', 'QnEwqUWTRlJc', 'Cook Islands', 49, 'Herero', 'LNX'),
('turnertheresa', 'Tyler Smith', 'B9puv3a4M86LxbtLca', 'Belize', 50, 'Ojibwa', 'WIN'),
('ggutierrez', 'Mary Sandoval', 'nc4EV6cHJYOB', 'Turks and Caicos Islands', 43, 'Amharic', 'WIN'),
('kellyjames', 'Christina Vaughan', 'JBeAp1on5vMv', 'Ukraine', 41, 'Vietnamese', 'LNX'),
('jimenezjames', 'Alexis Richardson', '0wGq90PqiTjbqDvGr0', 'Western Sahara', 62, 'Cree', 'MAC'),
('ablackburn', 'Antonio Munoz', 'aU4EuPnnVI5pJ4YKBzX', 'Northern Mariana Islands', 46, 'Tsonga', 'MAC'),
('nashchad', 'Marcia Henry', 'tenX2S2ZBhu3gnf8', 'Maldives', 55, 'Kannada', 'WIN'),
('alexis67', 'Samantha Miller', '2QQiotHq', 'Micronesia', 33, 'Zhuang', 'LNX'),
('griffitholivia', 'Lisa Graham MD', 'wmExB7zAl5onHeGURo', 'French Guiana', 22, 'Sichuan Yi', 'WIN'),
('julia27', 'Steven Carson', 'ix4ZjsAoy8as', 'San Marino', 60, 'Bihari languages', 'MAC'),
('banksnancy', 'Leah Martinez', '6UZ8b39CrrmB6W4X', 'Saint Lucia', 59, 'Sichuan Yi', 'WIN'),
('nharris', 'Tammy Alvarez', 'ItYPruPt9meGHQ0i', 'Bahrain', 35, 'Manx', 'LNX'),
('qlewis', 'Noah Lawrence', 'pajEmRy4M', 'Burundi', 55, 'Pushto', 'LNX'),
('garciajermaine', 'Isaac Jones', 'RkjpqSYud0x7', 'Bhutan', 25, 'Russian', 'MAC'),
('williamssarah', 'Benjamin Wilcox', 'sD1o8Lb9', 'Cook Islands', 38, 'Abkhazian', 'LNX'),
('thomasrodriguez', 'Nicole Gonzalez', 'lhEq5GvHsG', 'Greece', 52, 'Romansh', 'WIN'),
('teresa72', 'Ryan Rich', 'qpoe7jxUewGEp', 'Somalia', 36, 'Tigrinya', 'WIN'),
('ashley04', 'Alyssa King', 'XbyxLxxn', 'Austria', 65, 'Pali', 'MAC'),
('gbruce', 'April Figueroa', 'uYV98BrcfIalz', 'Micronesia', 22, 'Azerbaijani', 'WIN'),
('woodscott', 'Paul Wright', 'acVagVpDo77fQ', 'Poland', 35, 'Ido', 'LNX'),
('kylepeterson', 'Krystal Ford', 'aHGlbLHHyCacQCQZodX', 'Armenia', 57, 'Greek', 'WIN'),
('markoliver', 'Glenn Jones', 'zZ8ZoWKVbGG', 'Samoa', 53, 'Twi', 'MAC'),
('michael27', 'Annette Clarke', 'XJ0PLHsIKOS75', 'Montserrat', 40, 'Polish', 'WIN'),
('lwhite', 'Angela Wu', 'DhfIjkmV7H', 'Singapore', 20, 'Uighur', 'WIN'),
('uperry', 'Bianca Garcia', 'HoHRed88bp5', 'Botswana', 38, 'Russian', 'LNX'),
('ohernandez', 'Dr. Ashley Davis', 'nPfzDlHFI9doI', 'Belarus', 61, 'Sardinian', 'MAC'),
('michael15', 'Jasmine Garcia', '2FkJ2xGwYo', 'South Africa', 28, 'Tigrinya', 'MAC'),
('bishopjoshua', 'Amy Manning', 'KRGRiOevHOs3bN', 'Azerbaijan', 26, 'Sango', 'LNX'),
('qgilbert', 'Teresa Miller', 'RxtBhOmd', 'Sao Tome and Principe', 41, 'Corsican', 'WIN'),
('dana32', 'Denise Palmer', 'EX9LgzyceIW', 'Ireland', 62, 'Chuvash', 'MAC'),
('marcusbauer', 'Jeffrey Davis', 'wHDm7pihMAuzNM', 'Qatar', 33, 'Yiddish', 'LNX'),
('eblake', 'Melissa Schmitt', 'Mnkwl6iFrglPO', 'Chad', 56, 'Walloon', 'MAC'),
('scottrodriguez', 'Sarah Wood', 'sy1Bq8izn', 'Mozambique', 23, 'Chechen', 'MAC'),
('dwilliams', 'Jason Miller', 'EX5qhUK34oy4Ow4fje', 'Holy See (Vatican City State)', 35, 'Latin', 'WIN'),
('grayjacob', 'Morgan Baxter', 'DLMDhh5WxsT31MF6yM', 'Samoa', 51, 'Dzongkha', 'MAC'),
('ledwards', 'Tiffany Johnston', 'esFbQ6QB4sz7GVN8DD', 'Hungary', 41, 'Tamil', 'MAC'),
('fmoore', 'Deborah Estrada', 'DQavXR8BAYFB', 'Anguilla', 38, 'Tibetan', 'LNX'),
('taracharles', 'Kenneth Perez', 'VzXCAD4lQw', 'Niue', 45, 'Sanskrit', 'LNX'),
('saramendoza', 'Joshua Williams', 'udbPn4LR', 'China', 59, 'Tibetan', 'MAC'),
('dana90', 'Joseph Duran', '3wfpQhQE', 'Grenada', 20, 'Zhuang', 'LNX'),
('connor43', 'Christopher Garcia', 'hf2xQ8cjNTs3d2SS', 'Japan', 44, 'Panjabi', 'WIN'),
